apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-guard
  labels: { app: green-guard }
spec:
  replicas: 2
  selector:
    matchLabels: { app: green-guard }
  template:
    metadata:
      labels: { app: green-guard }
      annotations:
        kubectl.kubernetes.io/restartedAt: "fa4c23aad328b70dbed0e4d02ca849c5cacbe866"
    spec:
      containers:
        - name: app
          image: ghcr.io/just2courageous/green-guard:main   # <-- your GHCR image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
